packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@scarf/scarf'
  - 'unrs-resolver'
  - 'core-js'

allowBuilds:
  '@scarf/scarf': true
  core-js: true
  unrs-resolver: true
  '@tailwindcss/postcss': true